import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AuthProvider from "./AuthPriovider";
import UserProvider from "./context/UserProvider";
import { getKindeServerSession } from "@kinde-oss/kinde-auth-nextjs/server";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Blog-Viewer",
  description: "Generated by create next app",
};

// Make this an async function since you need to fetch server-side data
export default async function RootLayout({ children }) {
  const { getUser, isAuthenticated } = getKindeServerSession();

  // Fetch user data
  const user = await getUser();
  const isAuth = await isAuthenticated();

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <UserProvider initialUser={user} isAuthenticatd={isAuth}>
            {children}
          </UserProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
